{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "from lxml import html\n",
    "import requests\n",
    "import unicodecsv as csv\n",
    "import argparse\n",
    "\n",
    "def parse(zipcode,filter=None):\n",
    "\n",
    "\tif filter==\"newest\":\n",
    "\t\turl = \"https://www.zillow.com/homes/for_sale/{0}/0_singlestory/days_sort\".format(zipcode)\n",
    "\telif filter == \"cheapest\":\n",
    "\t\turl = \"https://www.zillow.com/homes/for_sale/{0}/0_singlestory/pricea_sort/\".format(zipcode)\n",
    "\telse:\n",
    "\t\turl = \"https://www.zillow.com/homes/for_sale/{0}_rb/?fromHomePage=true&shouldFireSellPageImplicitClaimGA=false&fromHomePageTab=buy\".format(zipcode)\n",
    "\t\n",
    "\tfor i in range(5):\n",
    "\t\t# try:\n",
    "\t\theaders= {\n",
    "\t\t\t\t\t'accept':'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',\n",
    "\t\t\t\t\t'accept-encoding':'gzip, deflate, sdch, br',\n",
    "\t\t\t\t\t'accept-language':'en-GB,en;q=0.8,en-US;q=0.6,ml;q=0.4',\n",
    "\t\t\t\t\t'cache-control':'max-age=0',\n",
    "\t\t\t\t\t'upgrade-insecure-requests':'1',\n",
    "\t\t\t\t\t'user-agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36'\n",
    "\t\t}\n",
    "\t\tresponse = requests.get(url,headers=headers)\n",
    "\t\tprint(response.status_code)\n",
    "\t\tparser = html.fromstring(response.text)\n",
    "\t\tsearch_results = parser.xpath(\"//div[@id='search-results']//article\")\n",
    "\t\tproperties_list = []\n",
    "\t\t\n",
    "\t\tfor properties in search_results:\n",
    "\t\t\traw_address = properties.xpath(\".//span[@itemprop='address']//span[@itemprop='streetAddress']//text()\")\n",
    "\t\t\traw_city = properties.xpath(\".//span[@itemprop='address']//span[@itemprop='addressLocality']//text()\")\n",
    "\t\t\traw_state= properties.xpath(\".//span[@itemprop='address']//span[@itemprop='addressRegion']//text()\")\n",
    "\t\t\traw_postal_code= properties.xpath(\".//span[@itemprop='address']//span[@itemprop='postalCode']//text()\")\n",
    "\t\t\traw_price = properties.xpath(\".//span[@class='zsg-photo-card-price']//text()\")\n",
    "\t\t\traw_info = properties.xpath(\".//span[@class='zsg-photo-card-info']//text()\")\n",
    "\t\t\traw_broker_name = properties.xpath(\".//span[@class='zsg-photo-card-broker-name']//text()\")\n",
    "\t\t\turl = properties.xpath(\".//a[contains(@class,'overlay-link')]/@href\")\n",
    "\t\t\traw_title = properties.xpath(\".//h4//text()\")\n",
    "\t\t\t\n",
    "\t\t\taddress = ' '.join(' '.join(raw_address).split()) if raw_address else None\n",
    "\t\t\tcity = ''.join(raw_city).strip() if raw_city else None\n",
    "\t\t\tstate = ''.join(raw_state).strip() if raw_state else None\n",
    "\t\t\tpostal_code = ''.join(raw_postal_code).strip() if raw_postal_code else None\n",
    "\t\t\tprice = ''.join(raw_price).strip() if raw_price else None\n",
    "\t\t\tinfo = ' '.join(' '.join(raw_info).split()).replace(u\"\\xb7\",',')\n",
    "\t\t\tbroker = ''.join(raw_broker_name).strip() if raw_broker_name else None\n",
    "\t\t\ttitle = ''.join(raw_title) if raw_title else None\n",
    "\t\t\tproperty_url = \"https://www.zillow.com\"+url[0] if url else None \n",
    "\t\t\tis_forsale = properties.xpath('.//span[@class=\"zsg-icon-for-sale\"]')\n",
    "\t\t\tproperties = {\n",
    "\t\t\t\t\t\t\t'address':address,\n",
    "\t\t\t\t\t\t\t'city':city,\n",
    "\t\t\t\t\t\t\t'state':state,\n",
    "\t\t\t\t\t\t\t'postal_code':postal_code,\n",
    "\t\t\t\t\t\t\t'price':price,\n",
    "\t\t\t\t\t\t\t'facts and features':info,\n",
    "\t\t\t\t\t\t\t'real estate provider':broker,\n",
    "\t\t\t\t\t\t\t'url':property_url,\n",
    "\t\t\t\t\t\t\t'title':title\n",
    "\t\t\t}\n",
    "\t\t\tif is_forsale:\n",
    "\t\t\t\tproperties_list.append(properties)\n",
    "\t\treturn properties_list\n",
    "\t\t# except:\n",
    "\t\t# \tprint (\"Failed to process the page\",url)\n",
    "\n",
    "if __name__==\"__main__\":\n",
    "\targparser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter)\n",
    "\targparser.add_argument('zipcode',help = '')\n",
    "\tsortorder_help = \"\"\"\n",
    "    available sort orders are :\n",
    "    newest : Latest property details,\n",
    "    cheapest : Properties with cheapest price\n",
    "    \"\"\"\n",
    "\targparser.add_argument('sort',nargs='?',help = sortorder_help,default ='Homes For You')\n",
    "\targs = argparser.parse_args()\n",
    "\tzipcode = args.zipcode\n",
    "\tsort = args.sort\n",
    "\tprint (\"Fetching data for %s\"%(zipcode))\n",
    "\tscraped_data = parse(zipcode,sort)\n",
    "\tprint (\"Writing data to output file\")\n",
    "\twith open(\"properties-%s.csv\"%(zipcode),'wb')as csvfile:\n",
    "\t\tfieldnames = ['title','address','city','state','postal_code','price','facts and features','real estate provider','url']\n",
    "\t\twriter = csv.DictWriter(csvfile, fieldnames=fieldnames)\n",
    "\t\twriter.writeheader()\n",
    "\t\tfor row in  scraped_data:\n",
    "\t\t\twriter.writerow(row)\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
